/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ntak_examples_jniexample_application_MainActivity */

#ifndef _Included_com_ntak_examples_jniexample_application_MainActivity
#define _Included_com_ntak_examples_jniexample_application_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
