/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ntak_examples_jniexample_subscriber_BackgroundRenderResourceSubscriber */

#ifndef _Included_com_ntak_examples_jniexample_subscriber_BackgroundRenderResourceSubscriber
#define _Included_com_ntak_examples_jniexample_subscriber_BackgroundRenderResourceSubscriber
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ntak_examples_jniexample_subscriber_BackgroundRenderResourceSubscriber
 * Method:    getBitmapJNI
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ntak_examples_jniexample_subscriber_BackgroundRenderResourceSubscriber_getBitmapJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
